using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.IdGenerators;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MongoDriverTest
{
    class Book
    {
        /// Gets or sets the unique identifier generated by the dbms.
        [BsonId(IdGenerator = typeof(CombGuidGenerator))]
        public Guid id { get; set; }

        /// Gets or sets the name of the book.
        public string Name { get; set; }

        /// Gets or sets the content of the book.
        public string Content { get; set; }

        /// Gets or sets the data. Cover photo of the book represented as a byte array.
        /// Added the BsonIgnore annotation so that field will not be added to the collection when serialization
        [BsonIgnore]
        public byte[] Data { get; set; }

        /// Gets or sets the image unique identifier. Reference to the photo file which is saved in GridFS collections
        public ObjectId ImageId { get; set; }
    }
}
